import '../../assets/css/global.css'

export const metadata = {
  title: 'Agenda',
  description: 'Generated by Alguém',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen m-0 p-0"> {children} </body>
    </html>
  )
}
